name: ChatGPT Clone App CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  eslint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} to Check Lint
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint

  test:
    needs: eslint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x to run Test
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
      - run: npm run test

  deploy:
    needs: [eslint, test]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Kinsta
        env:
          KINSTA_API_KEY: ${{ secrets.KINSTA_API_KEY }}
          APP_DEPLOYMENT_ID: ${{ secrets.APP_DEPLOYMENT_ID }}
        run: |
          curl -i -X POST \
            https://api.kinsta.com/v2/applications/deployments \
            -H "Authorization: Bearer $KINSTA_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "app_id": "$APP_DEPLOYMENT_ID",
              "branch": "main"
            }'


# Add more jobs if needed...
